### ISSUE TITLE
Size limits when using bftools to convert from czi to bigtiff

### ISSUE THREAD

**Issue by pergr** [ome/bioformats#2907]
I am new to bftools which I downloaded and started to use today to convert czi-files to bigtiff. The first conversion which should have produced a bigtiff file of several GB, failed with this message:

./bfconvert -bigtiff /import/1_20_12020_exf.czi /archive/tmp/work/1_20_12020_exf.tif 
/import/1_20_12020_exf.czi
ZeissCZIReader initializing /import/1_20_12020_exf.czi
[Zeiss CZI] -> /archive/tmp/work/1_20_12020_exf.tif [Tagged Image File Format]
Tile size = 1024 x 1024
	Series 0: converted 1/1 planes (100%)
Tile size = 1024 x 1024
Exception in thread "main" java.lang.IllegalArgumentException: Negative initial size: -1891557556
	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:74)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:327)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:277)
	at loci.formats.out.TiffWriter.saveBytes(TiffWriter.java:270)
	at loci.formats.tools.ImageConverter.convertTilePlane(ImageConverter.java:748)
	at loci.formats.tools.ImageConverter.convertPlane(ImageConverter.java:634)
	at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:563)
	at loci.formats.tools.ImageConverter.main(ImageConverter.java:884)

The czi-file is OK and I have verified that it can be converted to bigtiff with e.g. Zeiss' Zen Blue previewer. However, this manual solution is not a feasible one for converting a lot of files. 

I searched for an explanation to the problem on the web and found one for another, but similar problem:
"The code uses a ByteArrayOutputStream internally, which is limited in terms of its maximum size to Integer.MAX_VALUE - about 2GB"

Does anyone know if there is a fix/workaround for this problem.

Thank you.

Regards,
Per Grottum

**Comment by dgault** [comment]
Hi @pergr 

Apologies for the slow the response time. The image converter command line could be improved to be smarter with its use of tile sizes here, we are internally carrying out some benchmarking around tiling at the moment to try and find the optimal sizes for various scenarios.

In your case it is likely defaulting to attempt to convert the full plane at once which is leading to exception. If you manually set a more suitable tile size it should be able to cope better:

`bfconvert -tilex 512 -tiley 512 /path/to/input output-512x512-tiles.tiff`

**Comment by melissalinkert** [comment]
Closing as we have no way to reproduce the original issue, and numerous improvements to tiled conversion have been made in recent years. If similar problems persist with 8.5.0, feel free to re-open with additional information on how to reproduce (ideally by [uploading a sample file](https://bio-formats.readthedocs.io/en/latest/about/bug-reporting.html#sending-a-bug-report)).
