### ISSUE TITLE
Combine multiple metamorph files into sinlge .tif file

### ISSUE THREAD

**Issue by hummuscience** [ome/bioformats#3186]
I am trying to concatenate a time series of MetaMorph files into a singe .tif file with bfconvert (command line tool) but cannot make it work.

Is it at all possible? If so, what is the correct syntax?

This is what I am trying:

```
./bfconvert ~/mnt/Muad/ca-imaging/20180517/6tg-ko/ 6tg-ko.tif
/home/generalubuntu/mnt/Muad/ca-imaging/20180517/6tg-ko/
Exception in thread "main" java.io.FileNotFoundException: /home/generalubuntu/mnt/Muad/ca-imaging/20180517/6tg-ko (Is a directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:123)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:139)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:148)
	at loci.common.Location.getHandle(Location.java:324)
	at loci.common.Location.getHandle(Location.java:294)
	at loci.common.Location.getHandle(Location.java:284)
	at loci.common.Location.getHandle(Location.java:274)
	at loci.common.Location.checkValidId(Location.java:349)
	at loci.formats.ImageReader.getReader(ImageReader.java:177)
	at loci.formats.ImageReader.setId(ImageReader.java:839)
	at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:385)
	at loci.formats.tools.ImageConverter.main(ImageConverter.java:884)
```

these files can be used as example:

https://www.dropbox.com/s/2xvxycbwvm9p85k/test-series.zip?dl=0

**Comment by sbesson** [comment]
Hi @Cumol, the Bio-Formats command-line tools and more generally `IFormatReader.setId` method is expecting a file as the input and will not handle directories as suggested by the exception.

Converting Metamorph files into a single (OME-)TIFF should definitely work as long as you point the `bfconvert` utility to one of the [files consituting the fileset](https://docs.openmicroscopy.org/bio-formats/5.9.0/formats/dataset-table.html).

Using your test files and Bio-Formats 5.9.0, the two commands below should produce a single OME-TIFF and TIFF image:

```
sbesson@ls30630:Downloads $ bfconvert 23.001 23.ome.tiff
23.001
MetamorphTiffReader initializing 23.001
Reading IFDs
Populating metadata
Populating OME metadata
[Metamorph TIFF] -> 23.ome.tiff [OME-TIFF]
	Converted 1/10 planes (10%)
	Converted 10/10 planes (100%)
[done]
6.068s elapsed (3.5+325.3ms per plane, 1761ms overhead)
sbesson@ls30630:Downloads $ bfconvert 23.001 23.tiff
23.001
MetamorphTiffReader initializing 23.001
Reading IFDs
Populating metadata
Populating OME metadata
[Metamorph TIFF] -> 23.tiff [Tagged Image File Format]
	Converted 1/10 planes (10%)
	Converted 10/10 planes (100%)
[done]
6.69s elapsed (3.9+216.6ms per plane, 3615ms overhead)
```

**Comment by Cumol** [comment]
@sbesson wanted to try it out and wondered why it still gives the same error. It seems like th command line tools on the website are still the older version:

https://docs.openmicroscopy.org/bio-formats/5.8.2/users/comlinetools/index.html

When I run bfconvert -version it outputs 5.6.0 (from August 2017)

**Comment by Cumol** [comment]
I tried one full dataset and was able to convert it correctly.

Then tried another one and got the following output:

'''
23.001
MetamorphTiffReader initializing 23.001
Reading IFDs
Populating metadata
Populating OME metadata
Error reading IFD type at: 6
Exception in thread "main" java.lang.NullPointerException
	at loci.common.xml.XMLTools.sanitizeXML(XMLTools.java:298)
	at loci.formats.in.MetamorphTiffReader.parseFile(MetamorphTiffReader.java:628)
	at loci.formats.in.MetamorphTiffReader.initFile(MetamorphTiffReader.java:217)
	at loci.formats.FormatReader.setId(FormatReader.java:1397)
	at loci.formats.ImageReader.setId(ImageReader.java:842)
	at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:385)
	at loci.formats.tools.ImageConverter.main(ImageConverter.java:884)
'''

currently trying to find out how to replicate this with a small number of files

**Comment by hummuscience** [comment]
Wow! Thanks for still delivering this 6 years later <3
