### ISSUE TITLE
mkfake fails on ini file

### ISSUE THREAD

**Issue by joshmoore** [ome/bioformats#3346]
```
/tmp/fake $ mkfake .
/tmp/fake $ echo "sizeC=3" >>  screen.fake/Plate000/Run000/WellA000/Field000.fake.ini
/tmp/fake $ showinf screen.fake
Checking file format [Simulated data]
Initializing reader
FakeReader initializing screen.fake
Exception in thread "main" java.lang.NumberFormatException: For input string: "000.fake"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at loci.formats.in.FakeReader.extractTokensFromFakeSeries(FakeReader.java:1209)
	at loci.formats.in.FakeReader.initFile(FakeReader.java:555)
	at loci.formats.FormatReader.setId(FormatReader.java:1397)
	at loci.formats.ImageReader.setId(ImageReader.java:842)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1034)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1120)
```

**Comment by melissalinkert** [comment]
Closing in favor of https://github.com/ome/bioformats/pull/3499
