### ISSUE TITLE
CZI: FormatError on a single channel

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3401]
This issue originated from https://forum.image.sc/t/last-channel-3rd-right-most-fields-of-3-in-czi-file-displayed-as-zeros/25252/8

A sample file was provided in QA-27508, as of Bio-Formats 6.1.1 the issue is reproducible with the 3rd channel of the 9th series which returns 0 pixel values.

The stack trace is:
```
loci.formats.FormatException: ome.jxrlib.FormatError: ERROR: Unable to initialize decoder with stream: -106
	at loci.formats.services.JPEGXRServiceImpl.decompress(JPEGXRServiceImpl.java:60)
	at loci.formats.codec.JPEGXRCodec.decompress(JPEGXRCodec.java:84)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3820)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3776)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3771)
	at loci.formats.in.ZeissCZIReader.openBytes(ZeissCZIReader.java:394)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:156)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:229)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:348)
	at loci.formats.DimensionSwapper.openBytes(DimensionSwapper.java:249)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:348)
	at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:269)
	at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:260)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:186)
	at loci.plugins.in.ImagePlusReader.readProcessors(ImagePlusReader.java:422)
	at loci.plugins.in.ImagePlusReader.readPlanes(ImagePlusReader.java:387)
	at loci.plugins.in.ImagePlusReader.readImage(ImagePlusReader.java:282)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:243)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:221)
	at loci.plugins.in.ImagePlusReader.openImagePlus(ImagePlusReader.java:116)
	at loci.plugins.in.Importer.readPixels(Importer.java:149)
	at loci.plugins.in.Importer.run(Importer.java:86)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:229)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ome.jxrlib.FormatError: ERROR: Unable to initialize decoder with stream: -106
	at ome.jxrlib.JXRJNI.DecodeContext_decodeFirstFrame(Native Method)
	at ome.jxrlib.DecodeContext.decodeFirstFrame(DecodeContext.java:39)
	at ome.jxrlib.AbstractDecode.decodeFirstFrame(AbstractDecode.java:102)
	at ome.jxrlib.Decode.decodeFirstFrame(Decode.java:51)
	at loci.formats.services.JPEGXRServiceImpl.decompress(JPEGXRServiceImpl.java:54)
	... 29 common frames omitted
[WARN] Could not decompress block; some pixels may be 0
```

The original error seems to be UnsupportedFormat as below, which may be caused by a variety of different things:
https://github.com/glencoesoftware/jxrlib/blob/98e615dc5b08d684a270800aa631e3511b8c3efa/image/sys/windowsmediaphoto.h#L231

**Comment by melissalinkert** [comment]
Closing in favor of proposed fix: https://github.com/ome/bioformats/pull/3507
