### ISSUE TITLE
CV7000Reader breaks inside S3Handle.canHandleScheme

### ISSUE THREAD

**Issue by mtbc** [ome/bioformats#3419]
Combine the files from QA-27770 and QA-27774 for BF 6.2.0 to give:
```
Checking file format [Yokogawa CV7000]
Initializing reader
CV7000Reader initializing assay1.wpi
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at loci.common.S3Handle.canHandleScheme(S3Handle.java:128)
	at loci.common.Location.getHandle(Location.java:488)
	at loci.common.RandomAccessInputStream.<init>(RandomAccessInputStream.java:138)
	at loci.formats.in.MinimalTiffReader.initFile(MinimalTiffReader.java:446)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.in.CV7000Reader.initFile(CV7000Reader.java:337)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:843)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

**Comment by melissalinkert** [comment]
I couldn't easily reproduce this with 6.2.0 or 8.5.0, but `S3Handle` is scheduled for removal in https://github.com/ome/ome-common-java/pull/108. We should be able to close this issue once that is merged and released.
