### ISSUE TITLE
LIFReader fails on magic bytes in lof file

### ISSUE THREAD

**Issue by mtbc** [ome/bioformats#3511]
On `Image017_pmd_0.lof` from https://www.openmicroscopy.org/qa2/qa/feedback/29089/ Bio-Formats is giving me,
```
LIFReader initializing /home/mtbc/ome/apache_repo/29089/Image017_pmd_0.lof
loci.formats.in.LIFReader.initFile(/home/mtbc/ome/apache_repo/29089/Image017_pmd_0.lof)
Reading header
Finding image offsets
Looking for a block at 43; 0 blocks read
Location.mapFile: embedded-stream.raw -> null
Location.mapFile: embedded-stream.raw -> null
Failure during the reader initialization

loci.formats.FormatException: Invalid Memory Block: found magic bytes 298, expected 112
	at loci.formats.in.LIFReader.initFile(LIFReader.java:523) ~[bioformats_package.jar:6.4.0-SNAPSHOT]
	at loci.formats.FormatReader.setId(FormatReader.java:1389) ~[bioformats_package.jar:6.4.0-SNAPSHOT]
	at loci.formats.ImageReader.setId(ImageReader.java:843) ~[bioformats_package.jar:6.4.0-SNAPSHOT]
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650) ~[bioformats_package.jar:6.4.0-SNAPSHOT]
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035) [bioformats_package.jar:6.4.0-SNAPSHOT]
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121) [bioformats_package.jar:6.4.0-SNAPSHOT]
```
I also notice that `lof` is not listed as a filename extension on https://docs.openmicroscopy.org/bio-formats/6.3.1/supported-formats.html.

**Comment by melissalinkert** [comment]
LIF and LOF are two separate formats with similar headers.  LOF is not yet supported: https://trello.com/c/C13JeiIu/92-add-support-for-leica-xlef-xllf-lof-files

**Comment by mtbc** [comment]
Aha, perhaps simply the issue is that the LIF reader is trying to pick it up at all, thank you.

**Comment by mtbc** [comment]
For the record, the image I reference was taken with a Leica TCS SP8 confocal.
