### ISSUE TITLE
Recent ND2 files cannot be opened by bio-formats with NegativeArraySizeException

### ISSUE THREAD

**Issue by aarpon** [ome/bioformats#3517]
Some recent ND2 files (NIS Elements version 5.2, maybe earlier; you can find an example here: https://drive.google.com/file/d/1nrLmO6KAfUVNf6Ie5YXupZZf5LQLgoBd/view?usp=sharing) fail opening in bio-formats (up to version 6.3.1) with the following exception:

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 1798MB of 24263MB (7%)
 
java.lang.NegativeArraySizeException
	at loci.formats.in.NativeND2Reader.openBytes(NativeND2Reader.java:305)
	at loci.formats.DelegateReader.openBytes(DelegateReader.java:227)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:156)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:229)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:161)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.formats.DimensionSwapper.openBytes(DimensionSwapper.java:233)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:186)
	at loci.plugins.in.ImagePlusReader.readProcessors(ImagePlusReader.java:422)
	at loci.plugins.in.ImagePlusReader.readPlanes(ImagePlusReader.java:387)
	at loci.plugins.in.ImagePlusReader.readImage(ImagePlusReader.java:282)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:243)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:221)
	at loci.plugins.in.ImagePlusReader.openImagePlus(ImagePlusReader.java:116)
	at loci.plugins.in.Importer.readPixels(Importer.java:149)
	at loci.plugins.in.Importer.run(Importer.java:86)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.IJ.runPlugIn(IJ.java:182)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:499)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:72)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.IJ.runPlugIn(IJ.java:182)
	at ij.io.Opener.openWithHandleExtraFileTypes(Opener.java:516)
	at ij.io.Opener.openImage(Opener.java:370)
	at ij.io.Opener.openImage(Opener.java:242)
	at ij.io.Opener.open(Opener.java:109)
	at ij.io.Opener.openAndAddToRecent(Opener.java:291)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:192)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:159)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dgault** [comment]
Thanks for reporting the bug and providing a sample file. I was able to reproduce the exception using the latest Bio-Formats release (6.3.1) and neither of the ND2 options (chunkmap or native lib) had any impact.

Would it be possible to make the provided sample file available publicly under the CC-BY license?

**Comment by aarpon** [comment]
Hi,

sorry for the delay: I had to double-check with the owner of the file. The
file can be made available publicly under the terms of the CC-BY license.
Do I have to do something about it myself?

One more thing: we cropped the image in NIS Elements and the smaller file (
https://drive.google.com/file/d/1_qR5lagexpVq0rgkHvRAFhopBxPCL6ok/view?usp=sharing)
could be opened in Fiji successfully.

Thanks,
a2

**Comment by melissalinkert** [comment]
I believe https://forum.image.sc/t/error-while-opening-nd2-file/44700 is another example of this issue.  The problem appears to be specific to files with multiple channels that are stored interleaved when the total pixel count for a plane (X * Y * channels * bits) exceeds 2 GB.  Opening smaller tiles is a work-around in the meantime, but we should be able to fix this for the case when X * Y * bits is less than 2 GB.

**Comment by dgault** [comment]
An additional report of this issue comes from forum thread https://forum.image.sc/t/large-nd2-file-doesnt-open-negativearraysizeexception/54897. A new sample file reproduces the exception with Bio-Formats 6.6.1

**Comment by melissalinkert** [comment]
The file from https://forum.image.sc/t/error-while-opening-nd2-file/44700 no longer has this problem; https://github.com/openmicroscopy/data_repo_config/pull/590 adds it to the test repo.

I was not able to find the other files referenced here in `inbox`, though, so leaving this open until we can confirm that they are working as well.

**Comment by dgault** [comment]
A further report of this issue has been received for stitched files on the forum thread: https://forum.image.sc/t/large-nd2-file-doesnt-open-negativearraysizeexception/54897/10

**Comment by dominikl** [comment]
Still happens with latest version 8.0.0, see image.sc. reference above.

```
(bf) ➜  bftools ./showinf -version
Version: 8.0.0
Build date: 24 October 2024
VCS revision: b28636177d456992bf1b7199a7ce61d8af7c020b
(bf) ➜  bftools BF_MAX_MEM=16G ./showinf ../dan-iss-stitch_000_rm05_gas1-combined_final.nd2
Checking file format [Nikon ND2]
Initializing reader
ND2Reader initializing ../dan-iss-stitch_000_rm05_gas1-combined_final.nd2
...
Reading series #0 pixel data (0-4)
Exception in thread "main" java.lang.NegativeArraySizeException: -891306166
	at loci.formats.in.ND2Reader.openBytes(ND2Reader.java:320)
	at loci.formats.FormatReader.openBytes(FormatReader.java:922)
...
```

**Comment by melissalinkert** [comment]
> This issue has been mentioned on **Image.sc Forum**. There might be relevant details there:
> 
> https://forum.image.sc/t/nd2-container-file-does-not-open-with-bio-formats/104299/2

The file referenced here has now been copied to `inbox/imagesc-104299/`.

**Comment by dominikl** [comment]
There's another one on image.sc: https://forum.image.sc/t/large-nd2-file-one-system-can-open-but-nobody-else/108565/ 
(Respective file was copied to `inbox/imagesc-108565/`) Looks like the same issue to me.

**Comment by loicsauteur** [comment]
Hi,
The issue still happens in version 8.1.1, with an ND2 (created with NIS v5.21) image 23641 x 23641 x 2 (XYC).
The same image as an ome.tif (exported via NIS) can be opened by Bio-Formats.

However, using QuPath (version 0.6.0rc1, bio-formats v7.0.1; and version 0.5.0, bio-formats v7.3.1) can open the ND2 file.

Hope this helps in fixing the issue in future versions.
Thanks!

**Comment by ehrenfeu** [comment]
Cc @lguerard @rohangirishrao @cellkai @ehrenfeu (we're also potentially suffering from this issue).

**Comment by melissalinkert** [comment]
Thanks, @loicsauteur and @ehrenfeu. We're taking this out of the roadmap for 8.3.0 just due to time constraints, but will aim to pick up again for the next release.

Maybe I missed this, but had either of you uploaded data for this issue? If not, could you please put one of the affected files in the [Bio-Formats community on Zenodo](https://zenodo.org/communities/bio-formats/records)? That will help with testing any potential fixes.

**Comment by ehrenfeu** [comment]
I guess @loicsauteur will be able to generate such a dataset or even use an existing one.

**Comment by loicsauteur** [comment]
Hi @melissalinkert 
I uploaded an image to Zenodo.

I actually only tried to open the image on Windows (Win10), where I got the FIJI error (below). The OME XML metadata is read and displayed. (QuPath on Windows did open the image).
The same image **opens** on macOS (arm64) without error: `(Fiji Is Just) ImageJ 2.16.0/1.54p; Java 1.8.0_202 [64-bit]; Mac OS X 10.16; 146MB of 10667MB (1%)` with Bio Formats v8.1.1.


Here the error log of the windows error (OME XML metadata is read and displayed):
```
(Fiji Is Just) ImageJ 2.16.0/1.54p; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 161MB of 195973MB (<1%)

java.lang.NegativeArraySizeException
	at loci.formats.in.ND2Reader.openBytes(ND2Reader.java:320)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:169)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:231)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:350)
	at loci.formats.DimensionSwapper.openBytes(DimensionSwapper.java:251)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:350)
	at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:269)
	at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:260)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:336)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:336)
	at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:186)
	at loci.plugins.in.ImagePlusReader.readPlanes(ImagePlusReader.java:391)
	at loci.plugins.in.ImagePlusReader.readImage(ImagePlusReader.java:282)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:243)
	at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:221)
	at loci.plugins.in.ImagePlusReader.openImagePlus(ImagePlusReader.java:116)
	at loci.plugins.in.Importer.readPixels(Importer.java:165)
	at loci.plugins.in.Importer.run(Importer.java:87)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.IJ.runPlugIn(IJ.java:199)
	at net.imagej.legacy.command.LegacyCommand.run(LegacyCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by melissalinkert** [comment]
Thanks @loicsauteur. The Zenodo record is https://zenodo.org/records/16628927, for when we pick this up again.

**Comment by melissalinkert** [comment]
I can easily reproduce this issue with 8.1.1/8.2.0 and these datasets:

- https://github.com/ome/bioformats/issues/3517#issuecomment-3139956846
- https://github.com/ome/bioformats/issues/3517#issuecomment-2736062762
- https://github.com/ome/bioformats/issues/3517#issuecomment-2450459114

but 8.3.0 no longer shows the problem - all files can be opened normally without error and have been added to the test repository with https://github.com/openmicroscopy/data_repo_config/pull/698. #4309 is likely what fixed these files. If any similar errors occur with 8.3.0 (or future releases), it would be best to open as a separate issue as the underlying cause is likely different.
