### ISSUE TITLE
JPEG: IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3616]
Issue was raised on forum thread https://forum.image.sc/t/issue-with-bfconvert-and-big-jpg-images/43276/3 and a sample file was provided. The original issue was for a Java heap space issue, though there was also an Invalid Scan Line exception thrown.

Allocating extra memory allows the file reading to progress further (though it is extremely slow) and eventually fails with IndexOutOfBoundsException:

```
java.lang.IndexOutOfBoundsException: Index: 3062, Size: 2056
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at loci.formats.services.JPEGTurboServiceImpl.getTile(JPEGTurboServiceImpl.java:294)
	at loci.formats.services.JPEGTurboServiceImpl.getTile(JPEGTurboServiceImpl.java:249)
	at loci.formats.in.TileJPEGReader.openBytes(TileJPEGReader.java:81)
```

From debugging the dimensions appear to be correct, but the exception suggests that either the restartMarkers or more likely the restartInterval are incorrect. I tried modifying the restartInterval which allowed the process to finish without exception but the pixel data was clearly incorrect.

**Comment by dgault** [comment]
Tested the sample file in the most recent linked imagesc thread and it does indeed look to be the same bug as this Issue. With that sample file I was able to reproduce the bug (using Bio-Formats 7.1.0) and opening the file both with and without the cropped option. Opening the file without any cropping resulted in the below error:

```
java.lang.IndexOutOfBoundsException: Index: 2176, Size: 2056
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at loci.formats.services.JPEGTurboServiceImpl.getTile(JPEGTurboServiceImpl.java:296)
	at loci.formats.services.JPEGTurboServiceImpl.getTile(JPEGTurboServiceImpl.java:250)
	at loci.formats.in.TileJPEGReader.openBytes(TileJPEGReader.java:81)
```

I have copied the sample file from that post to `inbox/imagesc-90179`
