### ISSUE TITLE
CZI: NumberFormatException - parsing DetectorZoom

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3660]
Issue was raised through QA-29990 and a sample file has been provided highlighting the issue.

The stack trace from Insight is as follows:
```
java.lang.NumberFormatException: For input string: "1.5,1.5"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.(Double.java:608)
	at loci.formats.in.ZeissCZIReader.translateInformation(ZeissCZIReader.java:2361)
	at loci.formats.in.ZeissCZIReader.translateMetadata(ZeissCZIReader.java:1996)
	at loci.formats.in.ZeissCZIReader.initFile(ZeissCZIReader.java:1125)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:843)
```

I believe the issue is occurring at line https://github.com/ome/bioformats/blob/628a7eb56da1c043601e9184d9b269b86aea7125/components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java#L2364

**Comment by melissalinkert** [comment]
This appears to have been fixed in #3503, so the fix should be in OMERO 5.6.0 and later.
