### ISSUE TITLE
JPEG: Invalid scanline stride and Restart interval markers

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3773]
This issue was raised on imagesc thread https://forum.image.sc/t/jpeg-invalid-scanline-stride-and-restart-interval-and-markers-invalid/63045 and a sample file was provided that reproduces the issue with Bio-Formats 6.8.1.

The following stack trace is observed with both invalid scanline stride and invalid Restart interval and markers:
```
loci.formats.FormatException: java.lang.IllegalArgumentException: Invalid scanline stride
	at loci.formats.in.JPEGReader$DefaultJPEGReader.initFile(JPEGReader.java:206)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.DelegateReader.setId(DelegateReader.java:291)
	at loci.formats.in.JPEGReader.setId(JPEGReader.java:87)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
Caused by: java.lang.IllegalArgumentException: Invalid scanline stride
	at java.awt.image.ComponentSampleModel.getBufferSize(ComponentSampleModel.java:274)
	at java.awt.image.ComponentSampleModel.verify(ComponentSampleModel.java:252)
	at java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:170)
	at java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.awt.image.PixelInterleavedSampleModel.createCompatibleSampleModel(PixelInterleavedSampleModel.java:144)
	at javax.imageio.ImageTypeSpecifier.getSampleModel(ImageTypeSpecifier.java:1039)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1072)
	at javax.imageio.ImageReader.getDestination(ImageReader.java:2892)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1090)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1058)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at loci.formats.in.ImageIOReader.initImage(ImageIOReader.java:148)
	at loci.formats.in.ImageIOReader.initFile(ImageIOReader.java:121)
	at loci.formats.in.JPEGReader$DefaultJPEGReader.initFile(JPEGReader.java:203)
	... 7 common frames omitted
Exception in thread "main" java.io.IOException: Restart interval and markers invalid
	at loci.formats.services.JPEGTurboServiceImpl.initialize(JPEGTurboServiceImpl.java:222)
	at loci.formats.in.TileJPEGReader.reopenFile(TileJPEGReader.java:144)
	at loci.formats.in.TileJPEGReader.initFile(TileJPEGReader.java:121)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.DelegateReader.setId(DelegateReader.java:300)
	at loci.formats.in.JPEGReader.setId(JPEGReader.java:87)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

**Comment by melissalinkert** [comment]
This is expected behavior given the large XY size of the image, and the fact that no restart markers are present. Supporting this may be technically possible, but means that the whole 39984x29984 image must be decompressed at once; this will be very difficult to work with in practice, especially since there is no associated image pyramid. Pre-processing to tiled TIFF continues to be the recommendation for large JPEG images.
