### ISSUE TITLE
LIF: ArrayIndexOutOfBoundsException when parsing offsets

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3873]
Issue was raised via [QA-31234](https://www.openmicroscopy.org/qa2/qa/feedback/31234/) and a sample file was provided. Testing the sample file with Bio-Formats 6.10.1 was able to reproduce the same issue as described in the report.

The exception thrown is as below:
```
java.lang.ArrayIndexOutOfBoundsException: 52
	at loci.formats.in.LIFReader.initFile(LIFReader.java:587)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
```

This appears to be due to a mismatch in the number of offsets at https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/LIFReader.java#L587

**Comment by dgault** [comment]
A further report of this has been seen in `Insight Bug-32575`, the tack trace is as below. No sample file was included with the bug report:

```
java.lang.ArrayIndexOutOfBoundsException: 6
	at loci.formats.in.LIFReader.initFile(LIFReader.java:587)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at ome.formats.importer.OMEROWrapper$4.setId(OMEROWrapper.java:167)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelFiller.setId(ChannelFiller.java:234)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:293)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.Memoizer.setId(Memoizer.java:662)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:427)
	at ome.formats.importer.ImportCandidates.handleFile(ImportCandidates.java:576)
	at ome.formats.importer.ImportCandidates.execute(ImportCandidates.java:384)
	at ome.formats.importer.ImportCandidates.(ImportCandidates.java:222)
	at ome.formats.importer.ImportCandidates.(ImportCandidates.java:174)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.getImportCandidates(OMEROGateway.java:5894)
	at org.openmicroscopy.shoola.env.data.OmeroImageServiceImpl.importFile(OmeroImageServiceImpl.java:1104)
	at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.importFile(ImagesImporter.java:103)
	at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter.access$000(ImagesImporter.java:49)
	at org.openmicroscopy.shoola.env.data.views.calls.ImagesImporter$1.doCall(ImagesImporter.java:127)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dgault** [comment]
Another report of this issue has been received on forum thread https://forum.image.sc/t/problem-opening-stellaris-tilescan-lif-files-with-bio-formats/77489

A sample file reproducing the issue with Bio-Formats 6.12.0 has been provided
