### ISSUE TITLE
SVS: IndexOutOfBoundsException when opening lower resolutions

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3877]
Issue was raised on forum thread https://forum.image.sc/t/cannot-import-svs-file-using-bioformats/71840

A sample file reproducing the issue can be found at [GDC](https://portal.gdc.cancer.gov/files/fc037dde-4333-4ab7-b3a9-2b596cd16799) (tested with BF 6.10.1)

```
Exception in thread "BioFormats-ThumbLoader" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at loci.formats.in.MinimalTiffReader.openBytes(MinimalTiffReader.java:303)
	at loci.formats.in.SVSReader.openBytes(SVSReader.java:173)
```

The exception does not appear to occur with the highest level resolution and is likely linked to sub-resolution issues with the SVS reader

**Comment by dgault** [comment]
Issue appears to have been resolved by https://github.com/ome/bioformats/pull/3962
I will configure the sample file from this issue and add it to the data repo as a follow up.
