### ISSUE TITLE
OperettaReader: loci.formats.FormatException: Buffer too small

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#3894]
See [QA 31271](https://www.openmicroscopy.org/qa2/qa/feedback/31271/)

```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: import-file-exception
Parameters: {filename=<REMOVED>, stacktrace=loci.formats.FormatException: Buffer too small (got 1047600, expected 2095200).
	at loci.formats.FormatTools.checkBufferSize(FormatTools.java:1047)
	at loci.formats.FormatTools.checkPlaneParameters(FormatTools.java:1003)
	at loci.formats.in.MinimalTiffReader.openBytes(MinimalTiffReader.java:289)
	at loci.formats.in.OperettaReader.openBytes(OperettaReader.java:245)
...
```

**Comment by melissalinkert** [comment]
Only the import log was provided, there is no test plate. This error message matches a known issue with Operetta/Columbus/Harmony data in which multiple pixel types may be present within the same plate.
