### ISSUE TITLE
ND2: IllegalArgumentException during openBytes

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3909]
Issue was raised by QA-31330 and a sample file was provided that reproduces the issue with the latest Bio-Formats 6.11.0

The same issue occurs with and without the chunkmap option set, though with the default option you see the exception much quicker.

```
Parameters: {stacktrace=java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at loci.common.NIOFileHandle.read(NIOFileHandle.java:309)
	at loci.common.NIOFileHandle.read(NIOFileHandle.java:292)
	at loci.common.RandomAccessInputStream.read(RandomAccessInputStream.java:691)
	at loci.formats.in.NativeND2Reader.openBytes(NativeND2Reader.java:315)
	at loci.formats.DelegateReader.openBytes(DelegateReader.java:227)
	at loci.formats.ImageReader.openBytes(ImageReader.java:465)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:167)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:229)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:348)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:348)
	at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:269
```

**Comment by melissalinkert** [comment]
Retested with 7.0.0; I could not reproduce the exception with `showinf`, automated tests, or a simple loop over all tiles:

```
import loci.formats.ImageReader;
  
public class TileLoop {
  public static void main(String[] args) throws Exception {
    try (ImageReader r = new ImageReader()) {
      r.setId(args[0]);
      for (int s=0; s<r.getSeriesCount(); s++) {
        r.setSeries(s);
        for (int p=0; p<r.getImageCount(); p++) {
          for (int y=0; y<r.getSizeY(); y+=512) {
            for (int x=0; x<r.getSizeX(); x+=512) {
              r.openBytes(p, x, y, (int) Math.min(512, r.getSizeX()-x), (int) Math.min(512, r.getSizeY()-y));
            }
          }
        }
      }
    }
  }
}
```

https://github.com/openmicroscopy/data_repo_config/pull/590 adds the file to the test repo.
