### ISSUE TITLE
Zeiss CZI: Initialisation failure due to 'Invalid C index'

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#3996]
Issue was raised via QA-32932 and a sample file was provided that reproduces the issue with Bio-Formats 6.13.0

When attempting to open the file it fails during initialisation and the following stack trace is seen:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid C index: 1/1
	at loci.formats.FormatTools.getIndex(FormatTools.java:481)
	at loci.formats.FormatTools.getIndex(FormatTools.java:408)
	at loci.formats.FormatReader.getIndex(FormatReader.java:1150)
	at loci.formats.in.ZeissCZIReader.assignPlaneIndices(ZeissCZIReader.java:2181)
	at loci.formats.in.ZeissCZIReader.initFile(ZeissCZIReader.java:1002)
	at loci.formats.FormatReader.setId(FormatReader.java:1466)
	at loci.formats.ImageReader.setId(ImageReader.java:863)
```

**Comment by dominikl** [comment]
Another QA from UoD/Nightshade user: [QA 42439](https://qa.openmicroscopy.org/qa/feedback/42439/)
