### ISSUE TITLE
VolocityReader: IllegalArgumentException: newPosition > limit; Invalid series: 0

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4007]
See [QA 32953](https://www.openmicroscopy.org/qa2/qa/feedback/32953/)

```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: import-request-failure
Parameters: {stacktrace=java.lang.IllegalArgumentException: newPosition > limit: (951708 > 951707)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
	at java.base/java.nio.Buffer.position(Buffer.java:293)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:262)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:650)
	at loci.common.NIOFileHandle.skipBytes(NIOFileHandle.java:494)
	at loci.common.NIOFileHandle.skipBytes(NIOFileHandle.java:482)
	at loci.common.RandomAccessInputStream.skipBytes(RandomAccessInputStream.java:670)
	at loci.formats.in.VolocityReader.openBytes(VolocityReader.java:189)
...
```

I tried with the latest bioformat's showinf, but got a different error:
```
Checking file format [Volocity Library]
Initializing reader
VolocityReader initializing 2023 05 11 Mito morphology FH PFKB1 HIRA KO.mvd2
Exception in thread "main" java.lang.IllegalArgumentException: Invalid series: 0
	at loci.formats.FormatReader.seriesToCoreIndex(FormatReader.java:1298)
	at loci.formats.FormatReader.setSeries(FormatReader.java:969)
	at loci.formats.in.VolocityReader.initFile(VolocityReader.java:691)
...
```

**Comment by melissalinkert** [comment]
Placing all of the .dat files in a `Data` directory next to the .mvd2 file (as the reader expects) allows `setId` to finish. Volocity 4.1 can open this data, and a quick check suggests that the series count and image dimensions are correct, but the image data is definitely is not. Likely this is an issue with pixel offset calculation and/or compression type detection in `openBytes`.
