### ISSUE TITLE
MetaMorph nd file - Invalid image number

### ISSUE THREAD

**Issue by dgault** [ome/bioformats#4095]
Issue was raised on forum thread https://forum.image.sc/t/bioformat-omero-issue-with-metamorph-nd-files/84459

A sample dataset reproducing the issue with Bio-Formats 7.0.0 is available at `inbox/frederic-brau-nd-and-zstack`

The Bio-Formats stack trace is as below, the full log can be found on the forum thread:
```
stacktrace=loci.formats.FormatException: Invalid image number: 199 (series=0, imageCount=199)
	at loci.formats.FormatTools.checkPlaneNumber(FormatTools.java:1013)
	at loci.formats.FormatTools.checkPlaneParameters(FormatTools.java:1001)
	at loci.formats.in.MinimalTiffReader.openBytes(MinimalTiffReader.java:289)
	at loci.formats.in.MetamorphReader.openBytes(MetamorphReader.java:296)
	at loci.formats.in.MetamorphReader.openBytes(MetamorphReader.java:325)
	at loci.formats.ImageReader.openBytes(ImageReader.java:465)
```

**Comment by melissalinkert** [comment]
Note this is something we haven't seen before with Metamorph data - planes for each channel are split across 3 files, so that each file is less than 2GB. There is no indication of this in the .nd file, and so part of the issue is that the used file list is quite incorrect.
