### ISSUE TITLE
nd2: UnknownFormatException

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4108]
See [QA 40329](https://www.openmicroscopy.org/qa2/qa/feedback/40329/). I tried with the latest Insight, got the same error:
```
loci.formats.UnknownFormatException: Unknown file format: /Users/dom/40329/PAO1-WT_s3_14hPI-NHBEd55_DAPI_cy3-muc5AC_647-Phall_015.nd2
	at loci.formats.ImageReader.getReader(ImageReader.java:202)
	at loci.formats.ImageReader.setId(ImageReader.java:858)
	at ome.formats.importer.OMEROWrapper$4.setId(OMEROWrapper.java:167)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:660)
...
```

**Comment by melissalinkert** [comment]
This file also doesn't open in Nikon's NIS Elements Viewer. I do see ND2 metadata when opening in a hex editor, but it looks like the first part of the file was truncated or overwritten. Propose to close this on the grounds that the file is invalid.
