### ISSUE TITLE
SVS/MinimalTiffReader: FormatException: No IFDs found

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4192]
See [QA 41683](https://www.openmicroscopy.org/qa2/qa/feedback/41683/)

```
loci.formats.FormatException: No IFDs found
	at loci.formats.in.MinimalTiffReader.initFile(MinimalTiffReader.java:470)
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:609)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at ome.formats.importer.OMEROWrapper$4.setId(OMEROWrapper.java:167)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
...
```

**Comment by melissalinkert** [comment]
This file has likely been truncated, as the offset to the first IFD exceeds the length of the file. Both `tiffinfo` and ImageScope confirm that the file cannot be read, so there isn't much we can do.
