### ISSUE TITLE
LIF Reader: index out of bounds

### ISSUE THREAD

**Issue by jburel** [ome/bioformats#4199]
```
java.lang.ArrayIndexOutOfBoundsException: 32
	at loci.formats.in.LIFReader.initFile(LIFReader.java:587)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at ome.formats.importer.OMEROWrapper$4.setId(OMEROWrapper.java:167)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelFiller.setId(ChannelFiller.java:234)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:293)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.Memoizer.setId(Memoizer.java:662)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:427)

```

See https://www.openmicroscopy.org/qa2/qa/feedback/41723/

**Comment by melissalinkert** [comment]
A file was not submitted for QA 41723, correct? We can probably prevent this specific exception, but it may indicate a file that has other issues (which we wouldn't be able to test without the file itself).

**Comment by jburel** [comment]
No file submitted, I requested it
