### ISSUE TITLE
Bug: MicroManager 2.0.0 Division by 0

### ISSUE THREAD

**Issue by jburel** [ome/bioformats#4236]
Background 
https://forum.image.sc/t/micromanager-2-0-arithmeticexception-with-bio-formats/101407

**Comment by ilias-koulalis** [comment]
Are there any updates on this? I have run into the same issue with ```MetadataTools.populatePixels()``` while importing a TIFF image stack.

ImageJ Version: 1.54p
Bio-Formats Version: 8.1.1

Java Log:
```
java.lang.ArithmeticException: / by zero
	at loci.formats.MetadataTools.populatePixelsOnly(MetadataTools.java:315)
	at loci.formats.MetadataTools.populateMetadata(MetadataTools.java:262)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:151)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:116)
	at loci.formats.in.BaseTiffReader.initMetadataStore(BaseTiffReader.java:426)
	at loci.formats.in.TiffReader.initMetadataStore(TiffReader.java:236)
	at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:99)
	at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:610)
	at loci.formats.FormatReader.setId(FormatReader.java:1480)
	at loci.formats.in.TiffDelegateReader.setId(TiffDelegateReader.java:92)
	at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:498)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:141)
	at loci.plugins.in.Importer.showDialogs(Importer.java:156)
	at loci.plugins.in.Importer.run(Importer.java:77)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
```

However the following test script runs without exceptions and outputs "1 1"
```
import java.io.IOException;
import loci.formats.gui.BufferedImageReader;
import loci.formats.in.BaseTiffReader;
import loci.formats.in.TiffReader;
import loci.formats.in.MinimalTiffReader;
import java.lang.reflect.Method;
import java.io.File;

public class TiffReaderTest {

    public static void main(String[] args) throws Exception {

        String image = "Path";
        TiffReader imr = new TiffReader();

        imr.setId(image);
        BufferedImageReader r = BufferedImageReader.makeBufferedImageReader(imr);

        Method method = BaseTiffReader.class.getDeclaredMethod("initFile", String.class);

        method.setAccessible(true);
        method.invoke(imr, image);

        System.out.println(r.getEffectiveSizeC() + "\t" + r.getRGBChannelCount());

        }

    }
```

**Comment by melissalinkert** [comment]
No, there are no updates on this issue at the moment. Are you able to upload the TIFF file that demonstrates this issue to https://zenodo.org/communities/bio-formats? Do you see the same problem with Bio-Formats 8.5.0?

**Comment by melissalinkert** [comment]
https://zenodo.org/records/19708623 was uploaded for this. I can reproduce the error with 8.1.1 and 8.5.0. While the exception looks similar, this is a different problem from what was originally reported for this issue, so I will split into a separate issue.

The files in question have 658 IFDs, and ImageJ metadata indicating 658 Z sections. The first 46 IFDs have a single bit per sample, and the remainder have 16 bits per sample. The difference in pixel type tells `MinimalTiffReader` that the IFDs need to be split into separate series (lines ~484-523), but the ImageJ metadata overrides this and results in `sizeZ` being 658 with `imageCount` being 1, which causes the effective size C to be 0. One way to handle would be to expand the type of all planes to the widest type found, but I'm not sure about that as a general solution.

As noted in the Zenodo record, this is some of the original data from idr0068. Given that what was imported to https://idr.openmicroscopy.org/webclient/?show=project-2152 is converted from the original data, I suspect there were issues with the original data from the start, but I can't find relevant discussions to confirm (cc @sbesson).

**Comment by ilias-koulalis** [comment]
Thank you for catching this, I was about to link the zenodo upload.
